# Generated by Django 4.2.2 on 2023-06-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="name", new_name="category",
        ),
    ]
