# Generated by Django 4.2.2 on 2023-07-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_order_address_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
