# Generated by Django 4.2.2 on 2023-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_order_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="status", field=models.BooleanField(default=False),
        ),
    ]
